### ISSUE TITLE
je kan <slot> korter schrijven

### ISSUE THREAD

**Issue by Tolga1999** [mcphendriks/your-tribe-for-life-profile-card#16]
https://github.com/mcphendriks/your-tribe-for-life-profile-card/blob/d0c4776f6b187792aaf68d2aa1e832365e13bf03/src/routes/%2Blayout.svelte#L1-L3

super kort, gewoon dit
`<slot/>`

**Comment by mcphendriks** [comment]
Yes, thanks! did it
